version: '3'
services:
    php:
        build: ../design-patterns/docker/php
        container_name: frame-design-php
        hostname: php
        privileged: true
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
