version: '3'
services:
    nginx:
        image: nginx
        container_name: frame-design-nginx
        hostname: nginx
        privileged: true
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/html
            - ./docker/nginx/logs:/var/logs/nginx
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php
    php:
        build: ../design-patterns/docker/php
        container_name: frame-design-php
        hostname: php
        privileged: true
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
